# Config for Sarien and its variant, Arcada
[ids]
# AT keyboard is device 0001:0001
0001:0001

[main]
# f3
zoom = f11
# f5
camera = brightnessdown
# f6
scrolldown = brightnessup
leftmeta = capslock

[alt]
camera = kbdillumdown
scrolldown = kbdillumup
